######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 9 23:23:49 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += block.h window.h
SOURCES += block.cpp main.cpp window.cpp
